name: Push-to-EC2

# Trigger deployment only on push to master branch
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on main branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.HOST_DNS }}
          REMOTE_USER: ${{ secrets.USERNAME }}
  
  test:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - uses: actions/checkout@v3
      - name: Testing this app
        working-directory: ./
        run: |
          sudo apt-get update -y
          sudo apt-get install git -y
          sudo apt-get install -y gcc-c++ make
          sudo curl -sL https://rpm.nodesource.com/setup_16.x | sudo -E bash -
          sudo apt-get install -y nodejs          
          sudo npm install pm2 -g
          sudo npm i
          pm2 start server.js
          sudo ls
